# baseurl: "https://learnrwithdan.netlify.app/"
# copyright: Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved.
# paginate: 10
# theme: hugo-clarity
# disqusShortname: ''
# DefaultContentLanguage: en
# highlightjsTheme: "Night Owl"
# taxonomies:
#   category: categories
#   series: series
#   tag: tags
# outputs:
#   home:
#     - HTML
#     - RSS
#     - JSON

# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://example.com/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
