baseurl: "https://learnrwithdan.netlify.app/"
copyright: Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved.
paginate: 10
theme: hugo-clarity
disqusShortname: ''
DefaultContentLanguage: en
highlightjsTheme: "Night Owl"
taxonomies:
  category: categories
  series: series
  tag: tags
outputs:
  home:
    - HTML
    - RSS
    - JSON
